### ISSUE TITLE
Fail building the solution with Visual Studio

### ISSUE THREAD

**Issue by WangXuehan123** [stoani89/LaTeX2AI#17]
In the last step of Getting started, I failed building the solution with Visual Studio, where it shows that

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		The command "C:\Users\VirtualBox\Anaconda3\python.exe "D:\XuehanPackage\AI_CS6_SDK_Win_682.6.1\Adobe Illustrator CS6 SDK\samplecode\LaTeX2AI\forms\..\scripts\create_headers.py" cs" exited with code 3.	LaTeX2AIForms

I've not found the reason.

**Comment by stoani89** [comment]
The reason for this error is, that the pre-build script could not be executed because the (hard coded) python path could not be found.

I pushed a commit 3334d3fe0fc134bdf5bb2731a3e62d714a892f2d where this is fixed and the python path can be given via an environment variable `PYTHON_EXE` (also described in the updated documentation on that branch).

If you pull 3334d3fe0fc134bdf5bb2731a3e62d714a892f2d and set the said environment variable this error should not occur any more.

**Comment by WangXuehan123** [comment]
Succeed! 

But another probelm appear: 
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C2400	inline assembler syntax error in 'first operand'; found ':'	LaTeX2AI	D:\XuehanPackage\AI_CS6_SDK_Win_682.6.1\Adobe Illustrator CS6 SDK\samplecode\LaTeX2AI\l2a\tpl\StackWalker\Main\StackWalker\StackWalker.cpp	1071

**Comment by stoani89** [comment]
I am not familiar with that error. You can try to compile LaTeX2AI in `release` mode, then the `StackWalker` library will not be included. You can also open a new Issue with that error and a detailed description of your system (Visual Studio Version, etc.).

Since this issue is fixed, I will close it.
