### ISSUE TITLE
Fehler beim Laden von Zusatzmodulen (Error while loading plugins)

### ISSUE THREAD

**Issue by behinger** [stoani89/LaTeX2AI#41]
Hi!
I have no idea how to debug this, but still reporting in.

I copied the v0.0.3 files to: "C:\Program Files\Adobe\Adobe Illustrator 2020\Plug-ins\LaTexAI" and while starting Adobe Illustrator (either normal or admin), I get the following error (in German, but I saw other issue in german as well ;)).
![grafik](https://user-images.githubusercontent.com/10183650/116853630-aac0d200-abf6-11eb-812f-22fd1c4f9464.png)

Quite unspecific error.
Cheers, Bene

**Comment by stoani89** [comment]
This is most likely due to a incompatibility between the Illustrator SDKs. I uploaded a commit (8aa97c3) which should work with Illustrator 2020. Please try the following debug binaries: 
[LaTeX2AI_8aa97c3_debug_Illustrator2020.zip](https://github.com/stoani89/LaTeX2AI/files/6416534/LaTeX2AI_8aa97c3_debug_Illustrator2020.zip)


I don't have an running Illustrator 2020 version, so it is not tested. @behinger Could you run the test suite ![testing_light](https://user-images.githubusercontent.com/171502/102027380-e40db800-3da3-11eb-955b-bfcc8466f087.png) and send me the output?

**Comment by behinger** [comment]
ah.. sorry. I should read what version I had installed. Somehow autoupdate must have been deactivated - now the plugin runs
Still some trouble with miketex, but I guess that is to be expected (! LaTeX Error: File `standalone.cls' not found, even after reinstall of miktex :/)

I did try the plugin with 2020 before updating and it didnt show up - but maybe because I clicked the "dont show again" thing, I dont know if it was just ignored or threw a silent error. 

I think this can be savely closed

**Comment by stoani89** [comment]
The error `! LaTeX Error: File 'standalone.cls' not found` is most likely due to a missing package in MikTeX. Try to activate the _Always install missing packages on-the-fly_ option, see [here](https://miktex.org/howto/miktex-console).

If that doesn't help, feel free to open another issue.
